-- rime.lua

-- 加载自定义 Lua 模块
space_commit_raw_processor = require("space_commit_raw")
numeric_phrase_processor = require("numeric_phrase_processor")
panel_option_defaults = require("panel_option_defaults")
common_phrase_translator = require("common_phrase_translator")
common_phrase_filter = require("common_phrase_filter")
emoji_learning_processor = require("emoji_learning_processor")
emoji_second_position_processor = require("emoji_second_position_processor")
emoji_learning_translator = require("emoji_learning_translator")
chinese_abbreviation_learning_processor = require("chinese_abbreviation_learning_processor")
chinese_abbreviation_learning_translator = require("chinese_abbreviation_learning_translator")
translation_annotation_filter = require("translation_annotation_filter")
japanese_fuzzy_filter = require("japanese_fuzzy_filter")
mozc_v2_translator = require("mozc_v2_translator")
mozc_v2_prefix_translator = require("mozc_v2_prefix_translator")
mozc_mixed_filter = require("mozc_mixed_filter")
mozc_candidate_order_filter = require("mozc_candidate_order_filter")
direct_japanese_reading_filter = require("direct_japanese_reading_filter")
source_label_filter = require("source_label_filter")
google_cloud_candidate_filter = require("google_cloud_candidate_filter")
